### ISSUE TITLE
Not work with Gulp 4

### ISSUE THREAD

**Issue by Cryden** [sttk/gulp-showhelp#5]
D:\WebDevelopment\Project\webdevelopment\gw_starter\node_modules\gulp-showhelp\index.js:13
  return gulp.tasks[name];
                   ^

TypeError: Cannot read property 'help' of undefined
    at Gulp.gulp.task (D:\WebDevelopment\Project\webdevelopment\gw_starter\node_modules\gulp-showhelp\index.js:13:20)
    at Object.<anonymous> (D:\WebDevelopment\Project\webdevelopment\gw_starter\gulpfile.js:16:6)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at execute (C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:36:18)
    at Liftoff.handleArguments (C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\index.js:175:63)
    at Liftoff.execute (C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:203:12)
    at module.exports (C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:195:5)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:165:9
    at C:\Users\HP\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\v8flags\index.js:108:14

**Comment by sttk** [comment]
@Cryden Sorry, this plugin was created for gulp v3 only. 

However, Thanks to you I become motivated to support v4, too. I'll address it and release a new version soon!

**Comment by Cryden** [comment]
thnks
